version: "3.8"

services:
  backend:
    build: ./
    env_file: .env
    ports:
      - "8000:8000"
    command: npm start
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - QDRANT_URL=${QDRANT_URL}
      - QDRANT_API_KEY=${QDRANT_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
