version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  backend:
    build: ./
    env_file: .env
    depends_on:
      - qdrant
    ports:
      - "8000:8000"
    command: yarn start
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  qdrant_storage:
